### ISSUE TITLE
Cleanups around debug option "MESA_ENABLE_OMX_EGLIMAGE"

### ISSUE THREAD

**Issue by CapOM** [gpalsingh/mesa#10]
1) In entrypoint.c please remove the if debug_get_option_mesa_enable_omx_eglimage, it is not necessary

    if (debug_get_option_mesa_enable_omx_eglimage()) {
        tiz_check_omx (tiz_comp_register_role_eglimage_hook
                       (ap_hdl, (const OMX_U8 *) OMX_VID_DEC_AVC_ROLE, &egl_validation_hook));
    }

2) Remove DEBUG_GET_ONCE_BOOL_OPTION(mesa_enable_omx_eglimage, "MESA_ENABLE_OMX_EGLIMAGE", false) from the decoder
and set p_prc->use_eglimage = false; in h264d_prc_ctor. 

then in h264dprc.c::get_eglimage , add p_prc->use_eglimage = true if tiz_krn_claim_eglimage succeeds, and set it to false otherwise.

**Comment by gpalsingh** [comment]
Fixed by 
1) https://github.com/gpalsingh/mesa/commit/57262e9eedb2cf02cf73fc01b8ded4cd3bf595f1
2) https://github.com/gpalsingh/mesa/commit/c1eb9c85d93c3410e9ef9e5c08e4becaa516cdfd
