### ISSUE TITLE
EGLImage hook not working

### ISSUE THREAD

**Issue by gpalsingh** [gpalsingh/mesa#15]
After the rebase the [egl_image_validation_hook](https://github.com/gpalsingh/mesa/blob/gsoc-dev/src/gallium/state_trackers/omx_tizonia/entrypoint.c#L70) is no longer called by the IL core.

**Comment by CapOM** [comment]
What command line do you use ? I checked and it is working for me with 
https://github.com/CapOM/mesa/tree/gsoc-dev
https://github.com/CapOM/gst-omx/commits/tizonia-dev

**Comment by gpalsingh** [comment]
Ah I forgot to use the right pipeline. Thx.

Closing as false negative.

**Comment by gpalsingh** [comment]
Right pipeline for reference:
```
MESA_ENABLE_OMX_EGLIMAGE=1 GST_GL_API=gles2 GST_GL_PLATFORM=egl gst-launch-1.0 filesrc location=vid.mp4 ! qtdemux ! h264parse ! omxh264dec ! glimagesink
```
