### ISSUE TITLE
Build fail with egl wayland

### ISSUE THREAD

**Issue by AndyFurniss** [gpalsingh/mesa#16]
On gsoc-dev  I have to knock wayland out of my build to avoid -

make[4]: Entering directory '/mnt/sdb1/Gits/tiz-mesa/mesa/src/gallium/state_trackers/omx_tizonia'
  CC       h264dprc.lo
In file included from h264dprc.c:44:0:
../../../../src/egl/drivers/dri2/egl_dri2.h:47:30: fatal error: wayland-egl-priv.h: No such file or directory
compilation terminated.

This is how I am building mesa -

./autogen.sh --prefix=/usr --sysconfdir=/etc --enable-texture-float --enable-opencl --enable-omx-tizonia --with-egl-platforms=x11,drm,wayland --with-gallium-drivers=radeonsi,swrast --with-vulkan-drivers=radeon --enable-gbm --enable-shared-glapi --enable-glx-tls --with-dri-drivers= && make -j5

**Comment by gpalsingh** [comment]
I can reproduce this error. The command line I use is similar to this
```
./autogen.sh --enable-texture-float --enable-gles1 --enable-gles2 --enable-glx --enable-egl --enable-llvm --enable-shared-glapi --enable-gbm --enable-glx-tls --enable-dri --enable-osmesa --with-platforms=x11,drm --with-gallium-drivers=radeonsi,swrast --with-dri-drivers=radeon,swrast --enable-vdpau --enable-omx-bellagio --enable-omx-tizonia --enable-va --enable-debug --prefix=/usr && make -j8
```

**Comment by AndyFurniss** [comment]
OK, though I am a bit confused about the "similar" bit, your command will build fine for me (I removed the bellagio bit as I purged it).

What it won't do it make a mesa where the weston-simple-egl test works under weston.

 I can build your mesa OK to test tizonia with my command as long as I remove wayland from --with-egl-platforms=x11,drm,wayland - but that has the same effect = no egl with weston.

So did you really mean to say you can't reproduce this though you wrote you can, or was your pasted example missing the wayland bit that causes the fail?

**Comment by gpalsingh** [comment]
I just meant that I haven't really tested the egl support with wayland. About similar I use different prefix.

~~About the egl with wayland error that could be a bug in mesa itself. Julien might be able to tell better here.~~

**Comment by gpalsingh** [comment]
https://github.com/gpalsingh/mesa/commit/8b24c0952187c0c70098b303da0cd3bef1616e57 fixes the build error for me. You can test it out.

**Comment by AndyFurniss** [comment]
Yes, that fixes it for me, thanks.
