### ISSUE TITLE
segfault in tizonia using decode on AMD

### ISSUE THREAD

**Issue by AndyFurniss** [gpalsingh/mesa#17]
Testing decode I get a segfault in tizonia.
The code section the fault occurs at looks like it is trying to get encode params.
Encode does work for me,  with the resolution related fail cases that already has an issue open.

...
(gdb) run -f filesrc location=~/big_buck_bunny_480p_30mb.mp4 ! qtdemux ! h264parse ! omxh264dec ! fakesink
...
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fc85a688700 (LWP 1252)]
avcport_ctor (ap_obj=0x7fc850002c60, app=0x7fc85a687b58) at tizavcport.c:126
126           p_obj->pqtype_ = *p_pqtype;
(gdb) bt
#0  0x00007fc85af30e95 in avcport_ctor (ap_obj=0x7fc850002c60, app=0x7fc85a687b58) at tizavcport.c:126
#1  0x00007fc85af03c43 in factory_new (ap_class=0x7fc850009930) at tizobject.c:183
#2  0x00007fc8487370e5 in instantiate_h264d_input_port (ap_hdl=<optimized out>) at h264d.c:117
#3  0x00007fc85aef8e61 in init_and_register_role (ap_sched=ap_sched@entry=0x7fc8540046a0, a_role_pos=a_role_pos@entry=1) at tizscheduler.c:2682
#4  0x00007fc85aef979d in do_sparam (ap_role=0x7fffffffd8e0, ap_sched=<optimized out>) at tizscheduler.c:963
#5  0x00007fc85aef979d in do_sparam (ap_sched=0x7fc8540046a0, ap_state=<optimized out>, ap_msg=<optimized out>) at tizscheduler.c:1000
#6  0x00007fc85aef9e18 in dispatch_msg (ap_sched=ap_sched@entry=0x7fc8540046a0, ap_state=ap_state@entry=0x7fc8540057a0, ap_msg=0x840da0) at tizscheduler.c:2322
#7  0x00007fc85aef9f72 in il_sched_thread_func (p_arg=0x7fc8540046a0) at tizscheduler.c:2410
#8  0x00007fc863637434 in start_thread () at /lib/libpthread.so.0
#9  0x00007fc864c2106d in clone () at /lib/libc.so.6

**Comment by gpalsingh** [comment]
I can't seem to reproduce this same error. It doesn't work but not the same error.
Can you provide the gst pipeline? Is the result same with other videos too? The bellagio state tracker works with this pipeline?

I tried it with pipeline:

gst-launch-1.0 -f filesrc location=~/mp4_tests/10\ Second\ countdown.mp4.mp4 ! qtdemux ! h264parse ! omxh264dec ! videoconvert ! fakesink

and get this output:
```
Setting pipeline to PAUSED ...
mesa: for the -simplifycfg-sink-common option: may only occur zero or one times!
Pipeline is PREROLLING ...
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
Got EOS from element "pipeline0".
Execution ended after 0:00:00.631219168
Setting pipeline to PAUSED ...
Setting pipeline to READY ...
Setting pipeline to NULL ...
Freeing pipeline ...
```

Same result with both the bellagio and tizonia state trackers.

Using ximagesink with videoconvert works:
gst-launch-1.0 filesrc location= ~/mp4_tests/10\ Second\ countdown.mp4.mp4 ! qtdemux ! navseek seek-offset=2 ! h264parse ! omxh264dec ! videoconvert ! ximagesink

**Comment by AndyFurniss** [comment]
I've got the segfault whatever I've tried. 
Its the same displaying using your command above.
I tested bellagio before removing it and the tests I did were OK with that and fail with tizonia.

Strange the fakesink test fails for you - though I've never tried with videoconvert.
When testing bellagio "properly" rather than fakesink, I would use filesink  and get raw nv12, though rather big, it did allow to md5sum frames and compare to s/w dec. Other than a quirk where the last frame may differ (not visually), hwdec would always match swdec (ffmpeg) bit perfect.

**Comment by AndyFurniss** [comment]
Hmm, if your test file for the fakesink test is small enough then maybe it didn't fail - hard to judge < 1sec is quick...

The mesa message is IIRC harmless.

**Comment by gpalsingh** [comment]
Does https://github.com/gpalsingh/mesa/commit/aa9cd8d95e81ec0698604a386f7f5fc5c1ed8820 fix it?

**Comment by AndyFurniss** [comment]
Yes, decode is working with that :-)
Speed seems good, decode matches s/w on the one test I've done so far.
There is one nit that I'll look at more Tomorrow = a few frames missing at EOS.
Will close this and open a new issue for that when I've been able to test with more varied inputs.
