### ISSUE TITLE
Artefacts at the start of video

### ISSUE THREAD

**Issue by gpalsingh** [gpalsingh/mesa#2]
There is a chance that at start of the video it shows wrong output or no output at all.
Two examples:
![bug_screen1](https://user-images.githubusercontent.com/12171804/27931657-8cafef84-62b8-11e7-8580-aefb1ff092c3.png)
![bug_screen2](https://user-images.githubusercontent.com/12171804/27931660-925a51ae-62b8-11e7-8e7d-463dffa02dd7.png)

Normal run:
![bug_screen3](https://user-images.githubusercontent.com/12171804/27931664-95df6774-62b8-11e7-94c0-c416a4645ff0.png)

After few seconds video runs normally in all cases.

**Comment by CapOM** [comment]
I suspect this is because of the missing override of SetParameter. So some buffers could dropped during RE-allocation of the input buffers at the beginning of the stream.

**Comment by CapOM** [comment]
Could you create files h264dinport.c .h and in h264d_inport_init only add tiz_api_SetParameter. 
In h264d_inport_SetParameter set the nBufferSize like done in update_port_parameters in h264dprc.c

Except that it will be nBufferSize = pdef->nFrameWidth *nFrameHeight * 512...;

Indeed this is called when gst-omx call SetParameter with new width and height.

**Comment by gpalsingh** [comment]
I've been trying out the changes in https://github.com/gpalsingh/mesa/commit/7af9203461d28cb1c5e4a4c211fa50abf77668a0 but not working at the moment.
```
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
ERROR: from element /GstPipeline:pipeline0/GstQTDemux:qtdemux0: Internal data stream error.
Additional debug info:
qtdemux.c(6047): gst_qtdemux_loop (): /GstPipeline:pipeline0/GstQTDemux:qtdemux0:
streaming stopped, reason not-negotiated (-4)
ERROR: pipeline doesn't want to preroll.
Setting pipeline to NULL ...
Freeing pipeline ...
```

**Comment by CapOM** [comment]
In update_port_parameters also do an early return if width and height are same than current. I think this function will always early return now you overrides setparam. Except for resolution change.

**Comment by gpalsingh** [comment]
Updated commit: https://github.com/gpalsingh/mesa/commit/a94891ea537d7c587bcefec06f2c0ad4b204babf
Still no changes in results. Note that the chances of the artefacts appearing is random. I had to try a few times to see them again.

**Comment by CapOM** [comment]
I do not see the change in update_port_parameters in h264dprc.c I mentioned above?

No worries if it does not solve this issue in particular. In fact this will be useful for a more general purpose. Like avoiding unecessary reconf and correct buffer size.

Hard to explain in more details now, but I will next week.

Please add the change mentioned above in the same commit and let me know. Thx

**Comment by gpalsingh** [comment]
Added in https://github.com/gpalsingh/mesa/commit/a803fce97fcddc12f89c149d29ef701c86747552
Same results as before.
Okay sounds good.

**Comment by gpalsingh** [comment]
Added in https://github.com/gpalsingh/mesa/commit/f84f3fc11d25e6426b87ade2b998f55e9fba1856.
Same results as before.
Okay sounds good.

**Comment by CapOM** [comment]
I believe I fixed issue 2 (Artefacts at the start of video). The SetParameter was indeed the solution but you were doing a few mistakes :) so here are the fixes:

Last 4 commits of https://github.com/CapOM/mesa/commits/gsoc-dev
Plus last commit of https://github.com/CapOM/gst-omx/commits/tizonia-dev

This should also help with seeking and with dynamic resolution change while not entirely fixing it (I mean do not expect dynamic resolution change to work, like still missing 10% of the work).

Please integrate the 4 mesa commits in your dev branch. And squash (no split) them then into the decoder commit you sent for review. Mentioning "added SetParameter handling" into the v2 description.

For the gst-omx branch, I believe you should just use my branch as it is (no cherry-pick) as I rebased it against upstream and the commit about sequential flush was not trivial to rebase.

Cheers
Julien

**Comment by gpalsingh** [comment]
I can't seem to reproduce the issue after these fixes so closing for now. Thx!
