### ISSUE TITLE
SIGSEGV when using tee element - invalid buffer size 345600 < 353280

### ISSUE THREAD

**Issue by CapOM** [gpalsingh/mesa#5]
Reproduced with: gst-launch-1.0 filesrc location=anyvideo.mp4 ! qtdemux ! h264parse ! omxh264dec ! tee ! videoconvert ! ximagesink

I guess the allocated frame size with mesa/tiz is not big enough. Could be a bug in gst-omx also if it does not set a size big enough. Could be related to the offset/alignment.

Lets keep this around, not a priority since there is no crash if I remove the tee element in the pipeline above.

**Comment by CapOM** [comment]
I had a quick look and this is happening when doing OMX_AllocateBuffer on the output port of the decoder. Indeed the "tee" element prevent from proposing buffers from videoconvert to omxh264dec, i.e. it blocks the usage of OMX_UseBuffer. So it is good for testing but it fails.
I will keep looking.

**Comment by CapOM** [comment]
So there are the patch to fix this issue:

First one is a 1 line fix in tizonia: 
See https://github.com/tizonia/tizonia-openmax-il/issues/358

Second is a 2 lines fix in mesa:

"""
@@ -575,6 +580,8 @@ static OMX_ERRORTYPE update_port_parameters (h264d_prc_t * p_prc) {
     unsigned framesize = i_def->width * i_def->height;
PLUS      p_prc->in_port_def_.format.video.nFrameWidth = i_def->width;
PLUS      p_prc->in_port_def_.format.video.nFrameHeight = i_def->height;
     p_prc->in_port_def_.nBufferSize = framesize * 512 / (16*16);
"""
Please make it a patch in your mesa branch.

**Comment by gpalsingh** [comment]
This works for me. Thx!
