### ISSUE TITLE
Wrong colours in h264d when using EGLImage

### ISSUE THREAD

**Issue by gpalsingh** [gpalsingh/mesa#6]

**Comment by CapOM** [comment]
Maybe just doing something similar as https://github.com/gpalsingh/mesa/blob/gsoc-dev/src/gallium/state_trackers/va/postproc.c#L53 instead of the for loop around vl_compositor_set_rgba_layer

**Comment by CapOM** [comment]
I got confirmation that this should be done with vl_compositor_set_buffer_layer like in link above. (and not rgba layer)

**Comment by gpalsingh** [comment]
I made some changes https://github.com/gpalsingh/mesa/commit/07c14cff098c0398c3a8199e90aded1e3473ac77

With this I see the output but the colours are still wrong although not like the other case.

![image](https://user-images.githubusercontent.com/12171804/28861660-755754a4-777f-11e7-9438-4a72f6e6da0f.png)

**Comment by CapOM** [comment]
Fixed by https://github.com/CapOM/mesa/commit/fd42c7e89f0507fb6dd52f84851ee2522777497f . Please cherry-pick this commit into your branch.
The problem was that the color conversion matrix was not set so it default to identity.

**Comment by gpalsingh** [comment]
Works for me. Thanks!
