### ISSUE TITLE
Prepare commits to submit decoder to mesa-dev for review

### ISSUE THREAD

**Issue by CapOM** [gpalsingh/mesa#9]
- make clean commits for build and decoder, ideally it should be just 3 or 4 commits but let's see how it goes.
- indentation is 3 spaces in mesa/state_trackers
- cleanup any commented lines
- add more error handling if needed
- no eglimage in these commits

**Comment by gpalsingh** [comment]
Hi,
I made the commits here https://github.com/gpalsingh/mesa/commits/gsoc
The decoder works fine but there surfaced an error in the encoder at EOS which I'm looking into atm.

**Comment by CapOM** [comment]
Let's focus on the decoder for this ticket as this is about decoder, thx! I added some comments in the commits.

**Comment by CapOM** [comment]
They are merged now, thx!
